name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.4.0

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.*'
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Run lint
        run: npm run lint
